# fly.toml app configuration file generated for foodspot on 2023-07-06T15:00:02+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "foodspotters"
primary_region = "ams"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
