name: "Deploy App on Render"

on:
  push:
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Debugging:List Frontend Directory
        working-directory: frontend
        run: ls -l

      - name: Debugging:List Build Directory
        working-directory: frontend
        run: ls -l build

      - name: Upload Frontend Build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build

  build-backend:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Frontend Build
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: backend/src/main/resources/static

      - name: Verify Downloaded Files
        run: ls -l backend/src/main/resources/static

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B package --file backend/pom.xml

      - name: Upload Backend Jar
        uses: actions/upload-artifact@v4
        with:
          name: foodspotters.jar
          path: backend/target/foodspotters.jar

  push-to-docker-hub:
    runs-on: ubuntu-latest
    needs: build-backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Backend Jar
        uses: actions/download-artifact@v4
        with:
          name: foodspotters.jar
          path: backend/target

      - name: Verify Downloaded Jar
        run: ls -l backend/target

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: paffenst/capstone-foodspot:latest
          context: .

  deploy:
    name: deploy-to-render
    runs-on: ubuntu-latest
    needs: push-to-docker-hub
    environment:
      name: FoodSpotters
      url: https://capstone-foodspot.onrender.com/
    steps:
      - name: Render.com Deployment
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY }}
